import { OptionsStatesDDL } from '@/components/molecules/Reviews/OptionsStatesDDL'
import { SourceColumn } from '@/components/molecules/Reviews/SourceColumn'

export const REVIEWS_HEADER = [
  { id: 1, title: 'Date', field: 'date', withArrows: true },
  { id: 2, title: 'Location', field: 'location', withArrows: true },
  { id: 3, title: 'Rating', field: 'rating', withArrows: true },
  { id: 4, title: 'Source', field: 'source', withArrows: true },
  { id: 5, title: 'Summary', field: 'summary', withArrows: true },
  { id: 6, title: 'Status', field: 'status', withArrows: true },
  { id: 7, title: '', field: 'hrefSource', withArrows: false },
]

export const REVIEWS_DATA = [
  {
    id: '1',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 4.3,
    source: 'google',
    summary: 'summary text',
    status: '1',
    hrefSource: '/',
  },
  {
    id: '2',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 5,
    source: 'google',
    summary: 'summary text',
    status: '2',
    hrefSource: '/',
  },
  {
    id: '3',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 5,
    source: 'google',
    summary: 'summary text',
    status: '3',
    hrefSource: '/',
  },
  {
    id: '4',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 4.3,
    source: 'google',
    summary: 'summary text',
    status: '1',
    hrefSource: '/',
  },
  {
    id: '5',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 5,
    source: 'google',
    summary: 'summary text',
    status: '2',
    hrefSource: '/',
  },
  {
    id: '6',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 5,
    source: 'google',
    summary: 'summary text',
    status: '3',
    hrefSource: '/',
  },
  {
    id: '7',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 4.3,
    source: 'google',
    summary: 'summary text',
    status: '1',
    hrefSource: '/',
  },
  {
    id: '8',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 5,
    source: 'google',
    summary: 'summary text',
    status: '2',
    hrefSource: '/',
  },
  {
    id: '9',
    date: '03/09/2024',
    location: ['Clutch Automotive Friendswood', '206 S Friendswood Dr'],
    rating: 5,
    source: 'google',
    summary: 'summary text',
    status: '3',
    hrefSource: '/',
  },
]

export const REVIEWS_TABLE_CONFIG = {
  withCheckbox: true,
  withActions: true,
  withDelete: true,
  withEdit: true,
  withPagination: true,
  colorRows: [],
  multipleRows: ['location'],
  starRows: ['rating'],
  redirectButtons: ['hrefSource'],
  selecteds: [
    { field: 'status', element: (selected: any) => OptionsStatesDDL({ selected }) },
    { field: 'source', element: (source: string) => SourceColumn({ source }) },
  ],
}
